In [14]:
import torch
a = torch.zeros(2,2,2)
b = torch.ones(2,2,2)
c = torch.concat([a,b], dim=1)
print(c)
print(a)
print(b)

tensor([[[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
