In [2]:
import torch
a = torch.zeros(2,2,2)
b = torch.ones(2,2,2)
c = torch.concat([a,b], dim=1)
print(c)
print(a)
print(b)

c:\Users\Dell.DESKTOP-4AU2O53\anaconda3\envs\devoirs6390\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [30]:
a = torch.tensor([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
                   [[3, 4, 5, 6], [3, 4, 5, 6], [3, 4, 5, 6]]], dtype=float)
b = torch.tensor([1, 2, 1, 2])

mean = torch.mean(a, dim=-1, keepdim=True)
var = torch.var(a, dim=-1, keepdim=True)
print(mean)
x_norm = (a - mean) / torch.sqrt(var + 0.0000000001)
print(x_norm)

tensor([[[2.5000],
         [2.5000],
         [2.5000]],

        [[4.5000],
         [4.5000],
         [4.5000]]], dtype=torch.float64)
tensor([[[-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619]],

        [[-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619]]], dtype=torch.float64)


In [34]:
a = torch.tensor([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
                   [[3, 4, 5, 6], [3, 4, 5, 6], [3, 4, 5, 6]]], dtype=float)
print(a.shape)

b = torch.reshape(a, (1, 3, 8))

print(b.shape)
print(b)

torch.Size([2, 3, 4])
torch.Size([1, 3, 8])
tensor([[[1., 2., 3., 4., 1., 2., 3., 4.],
         [1., 2., 3., 4., 3., 4., 5., 6.],
         [3., 4., 5., 6., 3., 4., 5., 6.]]], dtype=torch.float64)


In [51]:
a = torch.tensor([[[[1,2,3,4], [1,2,3,4], [1,2,3,4]],
                   [[1,2,3,4], [1,2,3,4], [1,2,3,4]]],
                   [[[5,6,7,8], [5,6,7,8], [5,6,7,8]],
                    [[5,6,7,8], [5,6,7,8], [5,6,7,8]]]], dtype=float)
# print(a.shape)
# b = torch.reshape(a, (2, 3, 8))
# print(a)
# print()

c = a.permute(0, 2, 1, 3)
print(c.shape)
print(c.T.shape)
print("==== C ====")
print(c)
print("==== C.T ====")
print(c.T)

# d = torch.reshape(c, (2,3,8))
# print(d)

torch.Size([2, 3, 2, 4])
torch.Size([4, 2, 3, 2])
==== C ====
tensor([[[[1., 2., 3., 4.],
          [1., 2., 3., 4.]],

         [[1., 2., 3., 4.],
          [1., 2., 3., 4.]],

         [[1., 2., 3., 4.],
          [1., 2., 3., 4.]]],


        [[[5., 6., 7., 8.],
          [5., 6., 7., 8.]],

         [[5., 6., 7., 8.],
          [5., 6., 7., 8.]],

         [[5., 6., 7., 8.],
          [5., 6., 7., 8.]]]], dtype=torch.float64)
==== C.T ====
tensor([[[[1., 5.],
          [1., 5.],
          [1., 5.]],

         [[1., 5.],
          [1., 5.],
          [1., 5.]]],


        [[[2., 6.],
          [2., 6.],
          [2., 6.]],

         [[2., 6.],
          [2., 6.],
          [2., 6.]]],


        [[[3., 7.],
          [3., 7.],
          [3., 7.]],

         [[3., 7.],
          [3., 7.],
          [3., 7.]]],


        [[[4., 8.],
          [4., 8.],
          [4., 8.]],

         [[4., 8.],
          [4., 8.],
          [4., 8.]]]], dtype=torch.float64)


In [68]:
b = torch.tensor([[1,2],[3,4]])
# print(b)
# print(b.T)
a = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
# print(a)
# print(a.T)



tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 0],
         [3, 4]],

        [[5, 0],
         [7, 8]]])


In [78]:
a = torch.tensor([[[[1,2,3,4], [1,2,3,4], [1,2,3,4]],
                   [[1,2,3,4], [1,2,3,4], [1,2,3,4]]],
                   [[[5,6,7,8], [5,6,7,8], [5,6,7,8]],
                    [[5,6,7,8], [5,6,7,8], [5,6,7,8]]]], dtype=float)

print(a.shape)
indices = [(i, j) for i in range(0, a.shape[2]) for j in range(i+1, a.shape[3])]
row_indices = torch.tensor([i[0] for i in indices])
col_indices = torch.tensor([i[1] for i in indices])
a[:,:,row_indices, col_indices] = 0
print(a)

torch.Size([2, 2, 3, 4])
tensor([[[[1., 0., 0., 0.],
          [1., 2., 0., 0.],
          [1., 2., 3., 0.]],

         [[1., 0., 0., 0.],
          [1., 2., 0., 0.],
          [1., 2., 3., 0.]]],


        [[[5., 0., 0., 0.],
          [5., 6., 0., 0.],
          [5., 6., 7., 0.]],

         [[5., 0., 0., 0.],
          [5., 6., 0., 0.],
          [5., 6., 7., 0.]]]], dtype=torch.float64)


In [26]:
n_positions = 3
dimension = 4

n_positions_tensor = torch.arange(n_positions).unsqueeze(1)
dimension_tensor = torch.arange(dimension).unsqueeze(0)

print(dimension_tensor)
print(dimension_tensor[:,0::2])

PE = torch.zeros(n_positions, dimension)
PE[:,0::2] = torch.sin(n_positions_tensor.float() / (10000 ** ((dimension_tensor[:,0::2] // 2) / dimension)))
PE[:,1::2] = torch.sin(n_positions_tensor.float() / (10000 ** ((dimension_tensor[:,1::2] // 2) / dimension)))

print(PE)

tensor([[0, 1, 2, 3]])
tensor([[0, 2]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.8415, 0.8415, 0.0998, 0.0998],
        [0.9093, 0.9093, 0.1987, 0.1987]])


In [31]:
n_positions = 3
dimension = 4

n_positions_tensor = torch.arange(n_positions).unsqueeze(1)
dimension_tensor = torch.rand((3,4))

print(n_positions_tensor)
print(dimension_tensor)
print(dimension_tensor + n_positions_tensor)


tensor([[0],
        [1],
        [2]])
tensor([[0.3513, 0.4096, 0.0848, 0.9334],
        [0.3470, 0.9658, 0.2467, 0.3587],
        [0.3843, 0.7899, 0.3914, 0.0885]])
tensor([[0.3513, 0.4096, 0.0848, 0.9334],
        [1.3470, 1.9658, 1.2467, 1.3587],
        [2.3843, 2.7899, 2.3914, 2.0885]])


In [4]:
import torch
l = [torch.tensor(0.0), torch.tensor(1.1)]
l = torch.stack(l)
print(l)

c:\Users\Dell.DESKTOP-4AU2O53\anaconda3\envs\devoirs6390\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


TypeError: expected Tensor as element 0 in argument 0, but got int